### ISSUE TITLE
CI and Tests

### ISSUE THREAD

**Issue by lucymhdavies** [skybet/welcomebot#13]

**Comment by WheresAlice** [comment]
Assuming we're going with Travis, the `.travis.yml` file for building and pushing the Dockerfile will look something like:

```yml
sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=welcomebot
script:
  - docker build --tag skybet/welcomebot .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push skybet/welcomebot
  on:
    branch: master
```
